// Display names for dialogue seals. Historical figures use their courtesy names in titles.
export const SPEAKERS = {
  narrator: { name: 'Chronicle', cn: '史', color: '#3a2a1a' },
  liuBei: { name: 'Liu Bei', cn: '劉備', title: 'courtesy name Xuande 玄德', color: '#2e3e5e' },
  guanYu: { name: 'Guan Yu', cn: '關羽', title: 'courtesy name Yunchang 雲長', color: '#2a5a3a' },
  zhangFei: { name: 'Zhang Fei', cn: '張飛', title: 'courtesy name Yide 翼德', color: '#2a2420' },
  liuYan: { name: 'Liu Yan', cn: '劉焉', title: 'Inspector of You Province', color: '#6a1a1a' },
  zouJing: { name: 'Zou Jing', cn: '鄒靖', title: 'Commandant of Colonel rank', color: '#7a1c14' },
  chengYuanzhi: { name: 'Cheng Yuanzhi', cn: '程遠志', title: 'Yellow Turban commander', color: '#8a6a10' },
  dengMao: { name: 'Deng Mao', cn: '鄧茂', title: 'Yellow Turban lieutenant', color: '#8a6a10' },
  luZhi: { name: 'Lu Zhi', cn: '盧植', title: 'General of the Northern Capital Army', color: '#2a2a2a' },
  zhangJiao: { name: 'Zhang Jiao', cn: '張角', title: 'General of Heaven 天公將軍', color: '#a08010' },
  zhangLiang: { name: 'Zhang Liang', cn: '張梁', title: 'General of Man 人公將軍', color: '#a08010' },
  huangfuSong: { name: 'Huangfu Song', cn: '皇甫嵩', title: 'General of the Left of the Household', color: '#6a1a14' },
  caoCao: { name: 'Cao Cao', cn: '曹操', title: 'courtesy name Mengde 孟德', color: '#1c2436' },
  dongZhuo: { name: 'Dong Zhuo', cn: '董卓', title: 'Chancellor of State', color: '#5a1a3a' },
  luBu: { name: 'Lü Bu', cn: '呂布', title: 'courtesy name Fengxian 奉先', color: '#7a1414' },
  yuanShao: { name: 'Yuan Shao', cn: '袁紹', title: 'Leader of the Coalition', color: '#6a5a2a' },
  sunJian: { name: 'Sun Jian', cn: '孫堅', title: 'Tiger of Jiangdong', color: '#8a2a1a' },
  taoQian: { name: 'Tao Qian', cn: '陶謙', title: 'Governor of Xu Province', color: '#3a3a5a' },
  zhugeLiang: { name: 'Zhuge Liang', cn: '諸葛亮', title: 'Sleeping Dragon 臥龍', color: '#2a4a5a' },
  zhouYu: { name: 'Zhou Yu', cn: '周瑜', title: 'Grand Commander of Wu', color: '#8a2a1a' },
  sunQuan: { name: 'Sun Quan', cn: '孫權', title: 'Marquis of Wu', color: '#8a2a1a' },
  emperorXian: { name: 'Emperor Xian', cn: '漢獻帝', title: 'Liu Xie, last Son of Heaven of Han', color: '#1a1a1a' },
  mother: { name: 'Mother', cn: '母', color: '#5a3a3a' },
  father: { name: 'Father', cn: '父', color: '#4a3a2a' },
  elderWang: { name: 'Elder Wang', cn: '王老', title: 'Village head of Lousang', color: '#4a4030' },
  mei: { name: 'Mei', cn: '梅', title: 'your younger sister', color: '#7a3a4a' },
  smith: { name: 'Blacksmith Tie', cn: '鐵匠', title: 'Zhuo County forge', color: '#3a3a3a' },
  innkeeper: { name: 'Innkeeper Hou', cn: '侯掌櫃', title: 'Keeper of the Zhuo tavern', color: '#6a4a2a' },
  herald: { name: 'County Herald', cn: '縣吏', color: '#4a2a1a' },
  sergeant: { name: 'Drillmaster Guo', cn: '郭教頭', title: 'veteran of the Liang frontier wars', color: '#6a2a1a' },
  scout: { name: 'Scout', cn: '斥候', color: '#4a4a3a' },
  jianYong: { name: 'Jian Yong', cn: '簡雍', title: 'courtesy name Xianhe 憲和', color: '#3a4a3a' },
};
